import { describe, it, expect, beforeEach, vi } from 'vitest';

// Mock URL.createObjectURL for jsdom environment
global.URL.createObjectURL = vi.fn(() => 'blob:mock-url');
import {
  TelegramThemeBuilder,
  REQUIRED_PROPERTIES,
  THEME_PROPERTIES,
} from './index';
import type { ThemeColors } from './index';

// Sample extracted colors for testing
const sampleColors: ThemeColors = {
  primary: '#4a90d9',
  primaryLight: '#6ba8e8',
  primaryDark: '#3578c2',
  accent: '#58b6ed',
  accentLight: '#7fcdff',
  background: '#ffffff',
  backgroundSecondary: '#f7f7f7',
  backgroundTertiary: '#eeeeee',
  textPrimary: '#000000',
  textSecondary: '#666666',
  textMuted: '#999999',
  textOnPrimary: '#ffffff',
  online: '#5dc452',
  offline: '#999999',
  color1: '#4a90d9',
  color2: '#58b6ed',
  color3: '#5dc452',
  color4: '#f0a030',
  color5: '#e47272',
  color6: '#9b59b6',
};

const darkColors: ThemeColors = {
  primary: '#5288c1',
  primaryLight: '#6ba8e8',
  primaryDark: '#3b6a9e',
  accent: '#71bafa',
  accentLight: '#8ec8fc',
  background: '#17212b',
  backgroundSecondary: '#232f3d',
  backgroundTertiary: '#1c2731',
  textPrimary: '#e9e9e9',
  textSecondary: '#708499',
  textMuted: '#4c6f92',
  textOnPrimary: '#ffffff',
  online: '#5dc452',
  offline: '#708499',
  color1: '#5288c1',
  color2: '#71bafa',
  color3: '#5dc452',
  color4: '#efc274',
  color5: '#e47272',
  color6: '#a36ed6',
};

describe('TelegramThemeBuilder', () => {
  let builder: TelegramThemeBuilder;

  beforeEach(() => {
    builder = new TelegramThemeBuilder();
  });

  describe('constructor', () => {
    it('should create instance with default options', () => {
      const b = new TelegramThemeBuilder();
      expect(b).toBeInstanceOf(TelegramThemeBuilder);
      expect(b.getMode()).toBe('light');
      expect(b.getName()).toBe('Generated Theme');
    });

    it('should accept custom options', () => {
      const b = new TelegramThemeBuilder({
        mode: 'dark',
        name: 'Custom Theme',
        author: 'Test Author',
      });
      expect(b.getMode()).toBe('dark');
      expect(b.getName()).toBe('Custom Theme');
    });

    it('should default to light mode', () => {
      expect(builder.getMode()).toBe('light');
    });
  });

  describe('buildTheme', () => {
    it('should generate a theme object', () => {
      const theme = builder.buildTheme(sampleColors);

      expect(theme).toHaveProperty('name');
      expect(theme).toHaveProperty('content');
      expect(theme).toHaveProperty('properties');
      expect(theme).toHaveProperty('validation');
    });

    it('should generate valid theme content string', () => {
      const theme = builder.buildTheme(sampleColors);

      expect(typeof theme.content).toBe('string');
      expect(theme.content.length).toBeGreaterThan(0);
      expect(theme.content).toContain('windowBg:');
      expect(theme.content).toContain('windowFg:');
    });

    it('should include all required properties', () => {
      const theme = builder.buildTheme(sampleColors);

      for (const required of REQUIRED_PROPERTIES) {
        expect(theme.properties[required]).toBeDefined();
        expect(theme.content).toContain(`${required}:`);
      }
    });

    it('should generate properties with correct format', () => {
      const theme = builder.buildTheme(sampleColors);

      // Check that properties are hex colors without #
      for (const value of Object.values(theme.properties)) {
        expect(value).toMatch(/^[0-9a-f]{6}([0-9a-f]{2})?$/i);
      }
    });

    it('should map primary color to windowBgActive', () => {
      const theme = builder.buildTheme(sampleColors);

      expect(theme.properties.windowBgActive).toBe('4a90d9');
    });

    it('should map background color to windowBg', () => {
      const theme = builder.buildTheme(sampleColors);

      expect(theme.properties.windowBg).toBe('ffffff');
    });

    it('should map textPrimary to windowFg', () => {
      const theme = builder.buildTheme(sampleColors);

      expect(theme.properties.windowFg).toBe('000000');
    });

    it('should use theme name in content header', () => {
      const b = new TelegramThemeBuilder({ name: 'My Custom Theme' });
      const theme = b.buildTheme(sampleColors);

      expect(theme.content).toContain('// My Custom Theme');
    });

    it('should include author in content header', () => {
      const b = new TelegramThemeBuilder({ author: 'Test Author' });
      const theme = b.buildTheme(sampleColors);

      expect(theme.content).toContain('// Generated by Test Author');
    });

    it('should include mode in content header', () => {
      const theme = builder.buildTheme(sampleColors);

      expect(theme.content).toContain('// Mode: light');
    });
  });

  describe('buildTheme - dark mode', () => {
    let darkBuilder: TelegramThemeBuilder;

    beforeEach(() => {
      darkBuilder = new TelegramThemeBuilder({ mode: 'dark' });
    });

    it('should generate dark theme', () => {
      const theme = darkBuilder.buildTheme(darkColors);

      expect(theme.content).toContain('// Mode: dark');
    });

    it('should use dark colors for outgoing messages', () => {
      const theme = darkBuilder.buildTheme(darkColors);

      // Dark mode outgoing messages use primaryDark
      expect(theme.properties.msgOutBg).toBeDefined();
    });

    it('should darken incoming message background in dark mode', () => {
      const theme = darkBuilder.buildTheme(darkColors);

      expect(theme.properties.msgInBg).toBeDefined();
      // In dark mode, incoming bg should be different from main background
      expect(theme.properties.msgInBg).not.toBe(theme.properties.windowBg);
    });
  });

  describe('validateTheme', () => {
    it('should return valid result for complete theme', () => {
      const theme = builder.buildTheme(sampleColors);

      expect(theme.validation.valid).toBe(true);
      expect(theme.validation.errors).toHaveLength(0);
    });

    it('should detect missing required properties', () => {
      const incompleteProperties = { windowBg: 'ffffff' };
      const validation = builder.validateTheme(incompleteProperties);

      expect(validation.valid).toBe(false);
      expect(validation.missingProperties.length).toBeGreaterThan(0);
      expect(validation.errors.length).toBeGreaterThan(0);
    });

    it('should detect invalid color formats', () => {
      const invalidProperties = {
        ...builder.buildTheme(sampleColors).properties,
        windowBg: 'invalid',
      };
      const validation = builder.validateTheme(invalidProperties);

      expect(validation.valid).toBe(false);
      expect(validation.errors.some((e) => e.includes('Invalid color format'))).toBe(true);
    });

    it('should warn about missing optional properties', () => {
      const theme = builder.buildTheme(sampleColors);
      
      // Our builder should include most properties, but check that validation works
      expect(theme.validation.warnings.length).toBeGreaterThanOrEqual(0);
    });

    it('should list all missing properties', () => {
      const validation = builder.validateTheme({});

      expect(validation.missingProperties).toContain('windowBg');
      expect(validation.missingProperties).toContain('windowFg');
    });
  });

  describe('color utilities', () => {
    it('should normalize colors with # prefix', () => {
      const theme = builder.buildTheme({
        ...sampleColors,
        primary: '#4a90d9',
      });

      expect(theme.properties.windowBgActive).toBe('4a90d9');
    });

    it('should handle uppercase hex colors', () => {
      const theme = builder.buildTheme({
        ...sampleColors,
        primary: '#4A90D9',
      });

      expect(theme.properties.windowBgActive).toBe('4a90d9');
    });

    it('should add alpha channel to colors', () => {
      const theme = builder.buildTheme(sampleColors);

      // scrollBarBg should have alpha
      expect(theme.properties.scrollBarBg).toMatch(/[0-9a-f]{8}/i);
    });

    it('should generate valid alpha colors', () => {
      const theme = builder.buildTheme(sampleColors);

      // Check various alpha properties
      expect(theme.properties.msgSelectOverlay).toMatch(/^[0-9a-f]{8}$/i);
      expect(theme.properties.msgServiceBg).toMatch(/^[0-9a-f]{8}$/i);
    });
  });

  describe('file generation', () => {
    it('should create theme file blob', () => {
      const theme = builder.buildTheme(sampleColors);
      const blob = builder.createThemeFile(theme);

      expect(blob).toBeInstanceOf(Blob);
      expect(blob.type).toBe('application/octet-stream');
    });

    it('should create download URL', () => {
      const theme = builder.buildTheme(sampleColors);
      const url = builder.createDownloadUrl(theme);

      expect(typeof url).toBe('string');
      expect(url).toMatch(/^blob:/);
    });

    it('should generate valid filename', () => {
      const filename = builder.getFilename();

      expect(filename).toBe('generated-theme.tdesktop-theme');
    });

    it('should sanitize filename from theme name', () => {
      const b = new TelegramThemeBuilder({ name: 'My Cool Theme!!!' });
      const filename = b.getFilename();

      expect(filename).toBe('my-cool-theme.tdesktop-theme');
    });

    it('should handle special characters in filename', () => {
      const b = new TelegramThemeBuilder({ name: '  Spaces & Symbols @#$%  ' });
      const filename = b.getFilename();

      expect(filename).not.toContain(' ');
      expect(filename).not.toContain('@');
      expect(filename).not.toContain('#');
      expect(filename).toMatch(/\.tdesktop-theme$/);
    });
  });

  describe('theme content format', () => {
    it('should format properties as key: #value;', () => {
      const theme = builder.buildTheme(sampleColors);
      const lines = theme.content.split('\n').filter((l) => !l.startsWith('//') && l.trim());

      for (const line of lines) {
        // Property names can contain letters and numbers (e.g., msgFile1Bg)
        expect(line).toMatch(/^[a-zA-Z][a-zA-Z0-9]*: #[0-9a-f]+;$/i);
      }
    });

    it('should sort properties alphabetically', () => {
      const theme = builder.buildTheme(sampleColors);
      const lines = theme.content
        .split('\n')
        .filter((l) => !l.startsWith('//') && l.includes(':'));
      const keys = lines.map((l) => l.split(':')[0]);

      const sortedKeys = [...keys].sort();
      expect(keys).toEqual(sortedKeys);
    });

    it('should include header comments', () => {
      const theme = builder.buildTheme(sampleColors);
      const lines = theme.content.split('\n');

      expect(lines[0]).toMatch(/^\/\//);
      expect(lines[1]).toMatch(/^\/\//);
    });
  });

  describe('semantic color mapping', () => {
    it('should map online color to read markers', () => {
      const theme = builder.buildTheme(sampleColors);

      expect(theme.properties.historyOutIconFg).toBe('5dc452');
      expect(theme.properties.dialogsOnlineBadgeFg).toBe('5dc452');
    });

    it('should use accent color for links', () => {
      const theme = builder.buildTheme(sampleColors);

      expect(theme.properties.linkFg).toBe('58b6ed');
    });

    it('should use muted color for placeholders', () => {
      const theme = builder.buildTheme(sampleColors);

      expect(theme.properties.placeholderFg).toBe('999999');
    });

    it('should create distinct dialog backgrounds', () => {
      const theme = builder.buildTheme(sampleColors);

      expect(theme.properties.dialogsBg).toBe('ffffff');
      expect(theme.properties.dialogsBgOver).toBe('f7f7f7');
      expect(theme.properties.dialogsBgActive).toBe('4a90d9');
    });

    it('should map textOnPrimary for active items', () => {
      const theme = builder.buildTheme(sampleColors);

      expect(theme.properties.windowFgActive).toBe('ffffff');
      expect(theme.properties.dialogsNameFgActive).toBe('ffffff');
    });
  });

  describe('edge cases', () => {
    it('should handle minimum color set', () => {
      const minimalColors: ThemeColors = {
        primary: '#4a90d9',
        primaryLight: '#4a90d9',
        primaryDark: '#4a90d9',
        accent: '#4a90d9',
        accentLight: '#4a90d9',
        background: '#ffffff',
        backgroundSecondary: '#ffffff',
        backgroundTertiary: '#ffffff',
        textPrimary: '#000000',
        textSecondary: '#000000',
        textMuted: '#000000',
        textOnPrimary: '#ffffff',
        online: '#00ff00',
        offline: '#999999',
        color1: '#4a90d9',
        color2: '#4a90d9',
        color3: '#4a90d9',
        color4: '#4a90d9',
        color5: '#4a90d9',
        color6: '#4a90d9',
      };

      const theme = builder.buildTheme(minimalColors);

      expect(theme.validation.valid).toBe(true);
    });

    it('should handle very dark colors', () => {
      const darkColors: ThemeColors = {
        ...sampleColors,
        background: '#000000',
        textPrimary: '#ffffff',
      };

      const theme = builder.buildTheme(darkColors);

      expect(theme.properties.windowBg).toBe('000000');
      expect(theme.validation.valid).toBe(true);
    });

    it('should handle very light colors', () => {
      const lightColors: ThemeColors = {
        ...sampleColors,
        background: '#ffffff',
        textPrimary: '#000000',
      };

      const theme = builder.buildTheme(lightColors);

      expect(theme.properties.windowBg).toBe('ffffff');
      expect(theme.validation.valid).toBe(true);
    });

    it('should not throw on missing optional color properties', () => {
      expect(() => builder.buildTheme(sampleColors)).not.toThrow();
    });
  });

  describe('THEME_PROPERTIES', () => {
    it('should have 200+ properties defined', () => {
      expect(THEME_PROPERTIES.length).toBeGreaterThanOrEqual(200);
    });

    it('should have categories assigned', () => {
      for (const prop of THEME_PROPERTIES) {
        expect(prop.category).toBeDefined();
        expect(['window', 'chat', 'dialogs', 'history', 'media', 'profile', 'settings', 'intro', 'calls', 'misc']).toContain(prop.category);
      }
    });

    it('should have descriptions for all properties', () => {
      for (const prop of THEME_PROPERTIES) {
        expect(prop.description).toBeDefined();
        expect(prop.description.length).toBeGreaterThan(0);
      }
    });
  });

  describe('REQUIRED_PROPERTIES', () => {
    it('should have essential properties', () => {
      expect(REQUIRED_PROPERTIES).toContain('windowBg');
      expect(REQUIRED_PROPERTIES).toContain('windowFg');
      expect(REQUIRED_PROPERTIES).toContain('msgInBg');
      expect(REQUIRED_PROPERTIES).toContain('msgOutBg');
    });

    it('should all be included in THEME_PROPERTIES', () => {
      const allKeys = THEME_PROPERTIES.map((p) => p.key);
      
      for (const required of REQUIRED_PROPERTIES) {
        expect(allKeys).toContain(required);
      }
    });
  });

  describe('generated theme validation completeness', () => {
    it('should generate most properties from THEME_PROPERTIES', () => {
      const theme = builder.buildTheme(sampleColors);
      const generatedKeys = Object.keys(theme.properties);
      const allKeys = THEME_PROPERTIES.map((p) => p.key);
      
      // Should generate at least 70% of all properties
      const coverage = generatedKeys.filter((k) => allKeys.includes(k)).length / allKeys.length;
      expect(coverage).toBeGreaterThanOrEqual(0.7);
    });
  });
});
